import { runRouteAudits } from './_audit-helpers'

runRouteAudits('command', [
  { path: '/command', description: '总控舱 CommandApp', category: 'command', inBlueprint: true },
  { path: '/command/hub', description: '总控舱 - 模块首页', category: 'command', inBlueprint: false },
  { path: '/command/agents', description: '智能体总控台', category: 'command', inBlueprint: false },
  { path: '/command/agents/registry', description: '智能体注册表', category: 'command', inBlueprint: false },
  { path: '/command/agents/registry/demo-agent', description: '智能体详情（带参数）', category: 'command', inBlueprint: false },
  { path: '/command/agents/trigger', description: '智能体任务触发', category: 'command', inBlueprint: false },
  { path: '/command/agents/tasks', description: '智能体任务列表', category: 'command', inBlueprint: false },
  { path: '/command/agents/custom', description: '自定义智能体', category: 'command', inBlueprint: false },
  { path: '/command/agents/llm', description: 'LLM 管理', category: 'command', inBlueprint: false },
  { path: '/command/agents/capability-graph', description: '能力图谱', category: 'command', inBlueprint: false },
  { path: '/command/agents/dag-scheduler', description: 'DAG 调度器', category: 'command', inBlueprint: false },
  { path: '/command/agents/feedback', description: '反馈控制台', category: 'command', inBlueprint: false },
  { path: '/command/agents/model-upgrade', description: '模型升级', category: 'command', inBlueprint: false },
  { path: '/command/agents/data-labels', description: '数据标签管理', category: 'command', inBlueprint: false },
  { path: '/command/agents/api-config', description: 'API 配置', category: 'command', inBlueprint: false },
  { path: '/command/agents/skill-audit', description: 'Skill 核查', category: 'command', inBlueprint: false },
  { path: '/command/agents/optimization', description: '优化建议', category: 'command', inBlueprint: false },
  { path: '/command/agents/changelog', description: '更新日志', category: 'command', inBlueprint: false },
  { path: '/command/mcp-servers', description: 'MCP Server 管理', category: 'command', inBlueprint: false },
  { path: '/command/showcase', description: '组件示例库', category: 'command', inBlueprint: false },
  { path: '/command/health', description: '架构健康度仪表盘', category: 'command', inBlueprint: false },
  { path: '/command/monitor', description: '系统监控', category: 'command', inBlueprint: false },
  { path: '/command/config', description: '配置管理', category: 'command', inBlueprint: false },
  { path: '/command/test', description: '压力测试', category: 'command', inBlueprint: false },
])
