/**
 * @test_id V9-TEST-UT-057
 * @covers_docs [V9-DOC-BACK-013, V9-DOC-ARCH-008, V9-DOC-BACK-005, V9-DOC-BACK-008, V9-DOC-DATA-013]
 */
import { describe, expect, it, beforeEach } from 'vitest'
import { dataBridge } from '@/core/databridge'
import { EnvelopeFactory } from '@/core/envelope'
import { MODULE_ID, ENVELOPE_TARGET, ENVELOPE_ACTION, STORE_NAME } from '@/config/dbConfig'
import { db } from '@/data/db'
import { dataLayer } from '@/data/dataLayer'
import { scanWatchingSignals } from '@/services/trading/tradingService'
import type { DailyQuotes, KlineBar, Signal, Stock } from '@/data/types'

function buildHistory(count: number, factory: (i: number) => KlineBar): KlineBar[] {
  return Array.from({ length: count }, (_, i) => factory(i))
}

function buildQuotes(symbol: string, history: KlineBar[]): DailyQuotes {
  return {
    symbol,
    latest: history[history.length - 1]!,
    history,
    period: 'daily',
    adjust: 'qfq',
    updatedAt: Date.now(),
  }
}

async function seedWatchingStockWithDip(symbol: string): Promise<Stock> {
  await dataLayer.stocks.add({
    symbol,
    name: `${symbol} 测试`,
    researchStatus: 'watching',
    source: 'manual',
  })

  const history = buildHistory(40, (i) => {
    const close = i < 39 ? 100 + i * 0.1 : 85
    return {
      date: `2026-05-${String(i + 1).padStart(2, '0')}`,
      open: close - 0.5,
      high: close + 0.5,
      low: close - 1,
      close,
      volume: 10000,
      amount: 10000 * close,
    }
  })
  await dataLayer.dailyQuotes.save(buildQuotes(symbol, history))
  return (await dataLayer.stocks.get(symbol))!
}

describe('Signal Persistence', () => {
  beforeEach(async () => {
    await db.init()
    await db.reset()
    dataBridge.invalidateCache(STORE_NAME.stocks)
    dataBridge.invalidateCache(STORE_NAME.dailyQuotes)
    dataBridge.invalidateCache(STORE_NAME.signals)
  })

  it('应该持久化 a signal through DataBridge with tradinghub source', async () => {
    const signal: Signal = {
      id: 'sig-1',
      symbol: '000001.SZ',
      direction: 'buy',
      type: 'buy_dip',
      strategy: 'test',
      confidence: 0.7,
      rationale: '测试信号',
      snapshot: { rsi14: 25 },
      createdAt: Date.now(),
    }

    const envelope = EnvelopeFactory.create(
      {
        source: MODULE_ID.tradinghub,
        target: ENVELOPE_TARGET.db,
        action: ENVELOPE_ACTION.insertSignal,
        traceId: 'test-signal-1',
      },
      signal,
    )

    await dataBridge.forward(envelope)

    const saved = await dataLayer.signals.list()
    expect(saved).toHaveLength(1)
    expect(saved[0]!.symbol).toBe('000001.SZ')
    expect(saved[0]!.direction).toBe('buy')
  })

  it('应该reject analyzer writing signals', async () => {
    const envelope = EnvelopeFactory.create(
      {
        source: MODULE_ID.analyzer,
        target: ENVELOPE_TARGET.db,
        action: ENVELOPE_ACTION.insertSignal,
        traceId: 'test-signal-2',
      },
      {
        id: 'sig-2',
        symbol: '000001.SZ',
        direction: 'buy',
        type: 'buy_dip',
        confidence: 0.7,
        rationale: '测试信号',
        snapshot: {},
        createdAt: Date.now(),
      },
    )

    await expect(dataBridge.forward(envelope)).rejects.toThrow()
  })

  it('应该持久化 signals generated by scanWatchingSignals', async () => {
    await seedWatchingStockWithDip('000001.SZ')

    const signals = await scanWatchingSignals()
    expect(signals.length).toBeGreaterThan(0)

    const saved = await dataLayer.signals.list()
    expect(saved.length).toBeGreaterThan(0)
    expect(saved.some((s) => s.symbol === '000001.SZ')).toBe(true)
  })
})
