/**
 * @fileoverview UI 文本常量 — common 分组
 *
 * 从 uiText.ts 拆分而来，职责：通用 UI 文本（loading/error/confirm 等）
 *
 * @module constants/uiText/uiText.common
 * @created 2026-07-07 - 从 uiText.ts 拆分
 */

export const common = {
  loading: '加载中...',
  error: '加载失败',
  retry: '重试',
  empty: '暂无数据',
  confirm: '确认',
  cancel: '取消',
  save: '保存',
  delete: '删除',
  edit: '编辑',
  search: '搜索',
  reset: '重置',
  refresh: '刷新',
  back: '返回',
  next: '下一步',
  previous: '上一步',
  success: '操作成功',
  failed: '操作失败',
  noData: '暂无数据',
  loadMore: '加载更多',
  required: '必填',
  optional: '可选',
  unknown: '未知',
  submit: '提交',
  close: '关闭',
  add: '添加',
  update: '更新',
  view: '查看',
  detail: '详情',
  total: '共',
  item: '条',
  page: '页',
  perPage: '条/页',
  yes: '是',
  no: '否',
  all: '全部',
  none: '无',
  more: '更多',
  less: '更少',
  custom: '自定义',
  default: '默认',
  enabled: '已启用',
  disabled: '已禁用',
  active: '活跃',
  inactive: '未激活',
  pending: '待处理',
  processing: '处理中',
  completed: '已完成',
  running: '运行中',
  stopped: '已停止',
  paused: '已暂停',
  resumed: '已恢复',
  created: '已创建',
  modified: '已修改',
  deleted: '已删除',
  uploaded: '已上传',
  downloaded: '已下载',
  exported: '已导出',
  imported: '已导入',
  copied: '已复制',
  selected: '已选择',
  code: '代码',
  core: '核心',
} as const
