/**
 * @fileoverview UI 文本常量 — errors 分组
 *
 * 从 uiText.ts 拆分而来，职责：错误消息（网络/验证/输入/回测/评分等）
 *
 * @module constants/uiText/uiText.errors
 * @created 2026-07-07 - 从 uiText.ts 拆分
 */

export const errors = {
  networkError: '网络连接失败，请检查网络',
  serverError: '服务器错误，请稍后重试',
  forbidden: '无权限访问该内容',
  notFound: '请求的资源不存在',
  rateLimited: '请求过于频繁，请稍后重试',
  validation: '数据验证失败',
  invalidInput: '输入无效',
  missingField: '缺少必填字段',
  invalidFormat: '格式错误',
  invalidType: '类型错误',
  outOfRange: '超出范围',
  tooLong: '内容过长',
  tooShort: '内容过短',
  notMatched: '不匹配',
  alreadyExists: '已存在',
  notExists: '不存在',
  alreadyUsed: '已被使用',
  notAvailable: '不可用',
  notSupported: '不支持',
  notImplemented: '未实现',
  underMaintenance: '维护中',
  serviceUnavailable: '服务不可用',
  systemBusy: '系统繁忙',
  pleaseRetry: '请重试',
  pleaseWait: '请稍候',
  pleaseContact: '请联系管理员',
  pleaseTryLater: '请稍后再试',
  errorCode: '错误代码',
  errorMessage: '错误信息',
  errorDetails: '错误详情',
  errorStack: '错误堆栈',
  reportError: '报告错误',
  feedbackError: '反馈错误',
  // 驾驶舱/复盘专用
  noReviewData: '暂无复盘数据',
  noReviewDataTip: '完成交易后将自动生成AI复盘分析与交易洞察',
  aiDualEngine: '基于 AI 双引擎分析',
  totalTrades: '总交易数',
  winRate: '胜率',
  winRateTarget: '目标: 55%+',
  profitLossRatio: '盈亏比',
  profitLossRatioTarget: '目标: 1.5+',
  disciplineScore: '纪律评分',
  disciplineScoreTarget: '目标: 80+',
  aiInsight: 'AI洞察',
  errorAnalysis: '错误分析',
  discipline: '纪律',
  skills: '技能',
  action: '行动',
  aiDeepInsight: 'AI 深度洞察',
  pnlAttribution: '盈亏归因',
  dataPatterns: '数据规律',
  personalizedAdvice: '个性化建议',
  psychologicalProfile: '心理画像',
  topErrors: 'TOP5 错误',
  noErrorsDetected: '未检测到明显交易错误',
  major: '重要',
  minor: '轻微',
  planAdherenceRate: '计划遵守率',
  stopLossExecutionRate: '止损执行率',
  positionManagementScore: '仓位管理评分',
  emotionControlScore: '情绪控制评分',
  improvementSuggestions: '改善建议',
  beginner: '初级',
  intermediate: '进阶',
  expert: '专家',
  master: '大师',
  gapFromTarget: '距离目标还差',
  scoreUnit: '分',
  prioritySkills: '优先提升技能',
  highPriority: '高优',
  mediumPriority: '中优',
  lowPriority: '低优',
  skillMilestones: '技能里程碑',
  achieved: '已达成',
  targetDate: '目标日期',
  learningPath: '学习路径',
  hours: '小时',
  recommendedResources: '推荐学习资源',
  book: '书籍',
  course: '课程',
  article: '文章',
  tool: '工具',
  practice: '练习',
  executeNow: '立即执行',
  shortTerm: '短期(1月)',
  longTerm: '长期(3月)',
  riskAppetite: '风险偏好',
  aggressive: '激进',
  conservative: '保守',
  maxDrawdown: '最大回撤',
  concentration: '集中度',
  high: '高',
  low: '低',
  loadingFailed: '加载失败',
  clickToRetry: '点击重试',
  networkErrorShort: '网络错误',
  pageLoadFailed: '页面加载失败',
  operationFailed: '操作失败',
  pleaseSpecifyStockCode: '请指定股票代码',
  analysisEngineError: '分析引擎异常',
  calculationFailed: '计算失败',
  // 输入模块补充
  pleaseInputCodeAndName: '请输入代码和名称',
  addedSuccess: '已添加',
  addFailed: '添加失败',
  dataCollectionServiceError: '数据采集服务异常',
  refreshedPrice: '已刷新',
  refreshPriceFailed: '刷新行情失败',
  priceSuffix: '行情',
  batchTransitionComplete: '批量流转完成',
  batchTransitionPartialFailed: '部分失败',
  batchTransitionSuccess: '已批量流转',
  stockCount: '只标的',
  toStatus: '到',
  batchMoveComplete: '批量移入分组完成',
  batchMovedSuccess: '已批量移入',
  groupNameEmpty: '分组名称不能为空',
  groupNameExists: '分组名称已存在',
  createdGroup: '已创建分组',
  candidatePool: '意向候选池标的',
  collectedPrice: '已采行情',
  collectionService: '采集服务',
  checking: '检查中...',
  hotSectors: '热门板块',
  enterCandidateStock: '录入候选股票',
  fillCodeName: '填充代码/名称',
  directEntry: '直接录入意向候选池',
  selectedStock: '已选择',
  pleaseSelectEntryMode: '请选择录入方式',
  searchStockAdded: '搜索标的已录入意向候选池',
  stockCodePlaceholder: '股票代码，如 600519.SH',
  stockNamePlaceholder: '股票名称',
  defaultGroup: '默认分组',
  entryOnly: '仅录入',
  entryAndPullBasic: '录入并拉基础',
  entryAndPullAll: '录入并拉全部',
  collectionServiceStatus: '采集服务状态：',
  poolEmpty: '意向候选池为空',
  noStocksAdded: '还没有添加任何股票',
  poolEmptyTip: '你可以通过搜索录入、批量导入或从热门板块发现标的，开始构建你的研究股票池。',
  enterFirstStock: '录入第一只股票',
  stockPoolBoard: '股票池看板',
  refreshing: '刷新中...',
  refreshBoard: '刷新看板',
  kanbanView: '看板视图',
  listView: '列表视图',
  dataQualityFilter: '数据质量筛选',
  allQualityStatus: '全部质量状态',
  missingBasicData: '缺失基础数据',
  missingPriceData: '缺失行情数据',
  missingFinanceData: '缺失财务数据',
  selectedCount: '已选',
  batchArchive: '批量归档',
  batchMoveGroup: '批量移入分组',
  clearSelection: '清除选择',
  newPoolGroup: '新建股票池分组',
  newGroupDescription: '输入新分组名称，创建后可用于筛选与录入。',
  groupNamePlaceholder: '分组名称，如 核心持仓',
  // 回测模块补充
  sharpeRatio: '夏普比率',
  strategyBacktest: '策略回测',
  coreMetrics: '核心指标',
  navCurve: '净值曲线',
  navCurveDescription: '模拟回测区间内净值走势',
  tradeStats: '交易统计',
  totalTradeCount: '总交易次数',
  profitCount: '盈利次数',
  lossCount: '亏损次数',
  avgProfitStat: '平均盈利',
  avgLossStat: '平均亏损',
  profitLossRatioStat: '盈亏比',
  tradeDetails: '交易明细',
  simulatedTrades: '笔模拟交易',
  priceStat: '价格',
  pnlPercent: '盈亏(%)',
  buy: '买入',
  sell: '卖出',
  showFirst50: '仅显示前',
  trades: '条交易记录',
  backtestStrategy: '回测策略',
  initialCapitalUnit: '初始资金 (元)',
  backtestCalculation: '回测计算中...',
  runBacktest: '运行回测',
  clearResults: '清除结果',
  backtestFailed: '回测运行失败',
  notYetRunBacktest: '尚未运行回测',
  notYetRunBacktestTip: '在上方面板中选择回测策略、设置日期范围与初始资金，点击「运行回测」按钮开始模拟。',
  // 智能评分补充
  scoreBasisTitle: '评分依据补充说明',
  basicDataSnapshot: '基础数据快照',
  code: '代码',
  nameStat: '名称',
  priceStatLabel: '价格',
  pe: 'PE',
  pb: 'PB',
  roe: 'ROE',
  marketCapStat: '市值',
  supplementalMaterials: '补充资料',
  uploadedFiles: '上传文件',
  reportLength: '报告字数',
  usedModel: '使用模型',
  missingData: '缺失数据',
  noMissingFields: '无缺失字段',
  scoreBasisTitleStat: '评分结论依据',
  overallScore: '综合分',
  overallScoreDelta: '综合分Δ',
  maxChangeFactor: '最大变化因子',
  missingFields: '缺失字段',
  operationLog: '操作日志',
  supplementalUIInstructions: '补充界面说明',
  scoreCalculationRule: '综合分仅由"已取到有效数据"的维度等权平均计算；若某维度数据缺失，该维度显示为 N/A 且不计入综合分。',
  uploadFileRule: '上传本地文件或填写行业报告后，大模型会结合三源资料重新评分，未取到的字段不会使用默认值。',
  evidenceChainRule: '评分依据中的证据链来自模型对输入资料的引用，缺失数据会在"缺失数据"区域标红展示。',
  domesticModelTip: '如需使用 DeepSeek 等国内模型，请在 LLM 配置中填写对应的 OpenAI 兼容接口地址和模型名。',
  // 行业评分补充
  v4IndustryScore: 'V4 行业评分 · 第四次工业革命稀缺核心资源',
  scoreProgress: '评分进度',
  selectIndustry: '选择行业/赛道',
  pleaseSelectIndustry: '请选择行业',
  composite: '综合',
  shenwanLevel3: '申万三级',
  llmConfig: '大模型配置',
  baseURL: 'Base URL',
  apiKey: 'API Key',
  modelName: 'Model',
  llmNotConfigured: 'LLM 未配置',
  cannotStartScore: '无法开始评分',
  supplementalUpload: '补充资料上传',
  industryReport: '行业分析报告 / 资料',
  pasteReportTip: '粘贴最新行业研报、政策文件、新闻事件等...',
  scoring: '评分中...',
  runIndustryScore: '运行行业智能评分',
  configNotReady: 'LLM 未配置：请填写 baseURL、API Key 与模型名称后再运行评分',
  scoringPleaseWait: '评分运行中，请稍候...',
  scoreResult: '评分结果',
  overallScoreUnit: '综合分 / 5.0',
  compareLastTime: '较上次',
  aiSummary: 'AI 总结',
  // 补充缺失的通用属性
  core: '⭐',
  collapse: '收起',
  expand: '展开',
  add: '添加',
  cancel: '取消',
  date: '日期',
  target: '标的',
  direction: '方向',
  quantity: '数量',
  reason: '原因',
  price: '价格',
  time: '时间',
  model: '模型',
  startDate: '开始日期',
  endDate: '结束日期',
  total: '共',
  advanced: '高级',
  critical: '严重',
  inProgress: '进行中',
  completed: '已完成',
  video: '视频',
  neutral: '中性',
  no: '否',
  none: '无',
  connected: '已连接',
  disconnected: '未连接',
  quickActions: '快捷操作',
  batchImport: '批量导入',
  searchMode: '搜索模式：',
  processing: '处理中...',
  allGroups: '全部组',
  newGroup: '新建分组',
  failed: '失败',
  totalReturn: '总收益率',
  annualizedReturn: '年化收益率',
} as const
