/**
 * @fileoverview UI 文本常量 — analysis 分组
 *
 * 从 uiText.ts 拆分而来，职责：分析舱业务域 UI 文本（回测/评分/资讯/行业/因子等）
 *
 * @module constants/uiText/uiText.analysis
 * @created 2026-07-07 - 从 uiText.ts 拆分
  * @doc [V9-DOC-PROJ-066, V9-DOC-PROD-001, V9-DOC-PROJ-079, V9-DOC-PROJ-113, V9-DOC-PROJ-053]
*/

export const analysis = {
  backtest: {
    runButton: '运行回测',
    selectStrategy: '请选择回测策略',
    selectPeriod: '请选择回测周期',
    details: '回测详情',
    finalCapital: '最终资金',
    annualReturn: '年化收益率',
    maxDrawdown: '最大回撤',
    sharpeRatio: '夏普比率',
    winRate: '胜率',
    profitFactor: '盈利因子',
    trades: '交易次数',
    runningTip: '回测运行中，请稍候...',
    selectStrategyTip: '请先选择一个回测策略',
    selectPeriodTip: '请设置回测周期',
    noStrategy: '暂无可用策略',
    noPeriod: '请设置回测周期',
    confirmRun: '确认运行回测？',
    confirmCancel: '确认取消回测？',
    cancelRun: '取消回测',
    viewReport: '查看报告',
    exportReport: '导出报告',
    compareStrategy: '对比策略',
    strategyComparison: '策略对比',
    bestStrategy: '最优策略',
    worstStrategy: '最差策略',
  },
  scoreDoc: {
    versions: '版本记录',
    exportAll: '导出全部',
    selectStock: '请选择股票',
    noVersions: '暂无评分记录',
    generatedAt: '生成于',
    currentVersion: '当前版本',
    latestVersion: '最新版本',
    historyVersion: '历史版本',
    noDocument: '暂无评分文档',
    generating: '文档生成中...',
    regenerate: '重新生成',
    share: '分享文档',
    print: '打印文档',
    addComment: '添加评论',
    viewComments: '查看评论',
    noComments: '暂无评论',
    analysisReport: '分析报告',
    investmentAdvice: '投资建议',
  },
  news: {
    allCategories: '全部分类',
    allSentiments: '全部情感',
    noNews: '暂无相关新闻',
    generateMock: '生成测试数据',
    generating: '正在生成...',
    relatedStocks: '相关股票',
    source: '来源',
    publishTime: '发布时间',
    sentiment: '情感',
    keywords: '关键词',
    summary: '摘要',
    readMore: '阅读更多',
    shareNews: '分享资讯',
    bookmark: '收藏',
    bookmarked: '已收藏',
    reportError: '报错',
    reported: '已报错',
    noMore: '没有更多了',
    loadFailed: '加载失败',
    refreshNews: '刷新资讯',
    newestFirst: '最新优先',
    oldestFirst: '最早优先',
    hotNews: '热门资讯',
    breakingNews: '突发新闻',
    followUp: '跟进报道',
    originalReport: '原报道',
    breaking: '突发',
    reasoning: '推理',
    tryAdjustFilter: '试试调整筛选条件或稍后刷新',
  },
  industryScore: {
    selectIndustry: '请选择行业',
    runScore: '运行评分',
    scoring: '评分计算中...',
    scoreHistory: '评分历史',
    noHistory: '暂无评分记录',
    industryOverview: '行业概览',
    industryTrend: '行业趋势',
    industryRanking: '行业排名',
    subIndustry: '子行业',
    industryLeader: '行业龙头',
    industryAverage: '行业平均',
    industryCompare: '行业对比',
    selectSubIndustry: '选择子行业',
    runBatchScore: '批量评分',
    batchScoring: '批量计算中...',
    batchComplete: '批量完成',
    batchFailed: '批量失败',
    exportScore: '导出评分',
    scoreDetail: '评分详情',
    scoreChart: '评分图表',
    scoreTrend: '评分趋势',
    scoreDistribution: '评分分布',
    scoreComparison: '评分对比',
    scoreRanking: '评分排名',
    topIndustries: '领先行业',
    bottomIndustries: '落后行业',
    risingIndustries: '上升行业',
    fallingIndustries: '下降行业',
  },
  valuePit: {
    title: '价值洼地策略',
    noData: '暂无价值洼地策略数据',
    scoring: '正在计算价值洼地评分...',
  },
  hotSector: {
    title: '热门板块策略',
    noData: '暂无热门板块策略数据',
    heatmap: '板块热力图',
    rotationHeatmap: '板块轮动热力图',
    leadingTop5: '领涨 Top5',
    fallingTop5: '领跌 Top5',
    leadingSector: '领涨板块',
    fallingSector: '领跌板块',
    highTurnover: '高换手板块',
    capitalInflow: '资金流入',
    capitalOutflow: '资金流出',
  },
  multiFactor: {
    title: '多因子选股筛选',
    engine: '五维评分引擎',
  },
  factor: {
    contribution: '因子贡献',
    positiveContribution: '正向贡献',
    negativeContribution: '负向贡献',
    keyFactor: '关键因子',
    noData: '暂无因子贡献数据',
    loading: '正在计算因子贡献...',
    competitionPattern: '竞品格局',
    moat: '护城河',
    volatility: '波动',
    momentum: '动量',
    liquidity: '流动性',
    catalyst: '催化',
    chips: '筹码',
    technique: '技术',
    sentiment: '情绪',
    value: '估值',
  },
  scoreExplanation: {
    noData: '暂无评分解释',
    loadingFailed: '解释加载失败',
  },
  trend: {
    noData: '暂无趋势数据',
    noPreviousRecord: '暂无上一版本记录',
    noEffectiveChange: '各因子与上一版本无有效变化',
    risingTop: '上升因子 Top',
    fallingTop: '下降因子 Top',
  },
  rotation: {
    signal: '轮动信号',
    tentative: '试探',
    rotation: '轮动',
  },
  template: {
    quickEntry: '分析模板快捷入口',
  },
  score: {
    notScored: '尚未评分',
    notRated: '未评分',
    isFresh: '评分较新',
    suggestUpdate: '建议更新',
    overall: '综合',
  },
  intelligentScore: {
    configureLLM: '配置 LLM',
    selectStock: '选择股票',
    uploadFiles: '上传文件',
    startScore: '开始评分',
    scoring: '智能评分中...',
    viewHistory: '查看历史',
    noHistory: '暂无评分历史',
    scoreBasis: '评分依据',
    scoreFactors: '评分因素',
    scoreWeights: '评分权重',
    scoreResult: '评分结果',
    confidence: '置信度',
    credibility: '可信度',
    scoreExplanation: '评分说明',
    methodology: '评分方法',
    lastUpdated: '最后更新',
    refreshScore: '刷新评分',
    recalculate: '重新计算',
    cancelScore: '取消评分',
    confirmScore: '确认评分',
    scoreCompleted: '评分完成',
    scoreFailed: '评分失败',
    scorePending: '评分待处理',
    scoreCancelled: '评分已取消',
    retryScore: '重试评分',
    viewDetails: '查看详情',
    exportScore: '导出评分',
    printScore: '打印评分',
    shareScore: '分享评分',
    compareScore: '对比评分',
    scoreHistory: '评分历史',
    scoreTrend: '评分趋势',
    scoreDistribution: '评分分布',
    scoreRanking: '评分排名',
    topScore: '最高分',
    lowestScore: '最低分',
    averageScore: '平均分',
    scoreChange: '评分变化',
    scoreChangeRate: '评分变化率',
    opportunity: '机会提示',
  },
} as const
