/**
 * Organism 层注册表 — 业务领域复合组件
 * @doc [V9-DOC-FRONT-046]
 */
import type { ComponentEntry } from './registryTypes'

export const ORGANISM_REGISTRY: ComponentEntry[] = [
  // --- Pool 域 ---
  { name: 'PoolBoard', level: 'organism', sourcePath: 'src/components/organisms/pool/PoolBoard.tsx', targetPath: 'src/components/organisms/pool/PoolBoard.tsx', status: 'active', description: '股票池看板', consumers: ['PoolBoardPage', 'PoolBoardWidget', 'InputApp'] },
  { name: 'PoolCard', level: 'organism', sourcePath: 'src/components/organisms/pool/PoolCard.tsx', targetPath: 'src/components/organisms/pool/PoolCard.tsx', status: 'active', description: '股票池卡片', consumers: ['PoolBoard', 'PoolList', 'PoolColumn'] },
  { name: 'PoolColumn', level: 'organism', sourcePath: 'src/components/organisms/pool/PoolColumn.tsx', targetPath: 'src/components/organisms/pool/PoolColumn.tsx', status: 'active', description: '股票池列视图', consumers: ['PoolBoard', 'PoolBoardWidget'] },
  { name: 'PoolList', level: 'organism', sourcePath: 'src/components/organisms/pool/PoolList.tsx', targetPath: 'src/components/organisms/pool/PoolList.tsx', status: 'active', description: '股票池列表', consumers: ['PoolBoard', 'InputApp', 'PoolBoardPage'] },
  { name: 'usePoolDataFromStore', level: 'organism', sourcePath: 'src/components/organisms/pool/usePoolDataFromStore.ts', targetPath: 'src/components/organisms/pool/usePoolDataFromStore.ts', status: 'active', description: '股票池数据桥接 hook', consumers: ['PoolBoard', 'PoolList', 'PoolCard'] },
  { name: 'CollectionProgress', level: 'organism', sourcePath: 'src/components/organisms/pool/CollectionProgress.tsx', targetPath: 'src/components/organisms/pool/CollectionProgress.tsx', status: 'active', description: '采集进度', consumers: ['PoolBoardPage', 'InputDashboard'] },
  { name: 'StockNewsStats', level: 'organism', sourcePath: 'src/components/organisms/pool/StockNewsStats.tsx', targetPath: 'src/components/organisms/pool/StockNewsStats.tsx', status: 'active', description: '股票资讯统计', consumers: ['PoolBoardPage', 'PoolCard'] },
  { name: 'BatchCollectionPanel', level: 'organism', sourcePath: 'src/components/organisms/pool/BatchCollectionPanel.tsx', targetPath: 'src/components/organisms/pool/BatchCollectionPanel.tsx', status: 'active', description: '批量采集面板', consumers: ['CollectTaskPage', 'InputApp', 'PoolBoardPage'] },
  { name: 'StockOverviewCard', level: 'organism', sourcePath: 'src/components/organisms/pool/StockOverviewCard.tsx', targetPath: 'src/components/organisms/pool/StockOverviewCard.tsx', status: 'active', description: '个股总览卡片', consumers: ['PoolBoardPage', 'StockDetailPage', 'PoolCard'] },

  // --- Collection 域 ---
  { name: 'CollectionProgressPanel', level: 'organism', sourcePath: 'src/components/organisms/collection/CollectionProgressPanel.tsx', targetPath: 'src/components/organisms/collection/CollectionProgressPanel.tsx', status: 'active', description: '采集进度面板', consumers: ['CollectTaskPage', 'InputDashboard'] },
  { name: 'CollectionReportPanel', level: 'organism', sourcePath: 'src/components/organisms/collection/CollectionReportPanel.tsx', targetPath: 'src/components/organisms/collection/CollectionReportPanel.tsx', status: 'active', description: '采集汇报面板', consumers: ['CollectTaskPage', 'InputDashboard'] },

  // --- Analysis 域 ---
  { name: 'AnalysisTemplateCards', level: 'organism', sourcePath: 'src/components/organisms/analysis/hub/AnalysisTemplateCards.tsx', targetPath: 'src/components/organisms/analysis/hub/AnalysisTemplateCards.tsx', status: 'active', description: '分析模板卡片', consumers: ['AnalysisApp', 'HotSectorPage'] },
  { name: 'ScoreHistoryPanel', level: 'organism', sourcePath: 'src/components/organisms/analysis/score/ScoreHistoryPanel.tsx', targetPath: 'src/components/organisms/analysis/score/ScoreHistoryPanel.tsx', status: 'active', description: '评分历史面板', consumers: ['IntelligentScorePage', 'IndustryScorePage', 'TrendAndExplanation'] },
  { name: 'MultiPeriodTrendChart', level: 'organism', sourcePath: 'src/components/organisms/analysis/score/MultiPeriodTrendChart.tsx', targetPath: 'src/components/organisms/analysis/score/MultiPeriodTrendChart.tsx', status: 'active', description: '多周期趋势图', consumers: ['ScoreHistoryPanel', 'IntelligentScorePage', 'TrendAndExplanation'] },
  { name: 'ScoreFactorWaterfall', level: 'organism', sourcePath: 'src/components/organisms/analysis/score/ScoreFactorWaterfall.tsx', targetPath: 'src/components/organisms/analysis/score/ScoreFactorWaterfall.tsx', status: 'active', description: '因子瀑布图', consumers: ['IntelligentScoreExplanation', 'ScoreFactorDeltaPanel', 'ReviewWizard'] },
  { name: 'IntelligentScoreExplanation', level: 'organism', sourcePath: 'src/components/organisms/analysis/score/IntelligentScoreExplanation.tsx', targetPath: 'src/components/organisms/analysis/score/IntelligentScoreExplanation.tsx', status: 'active', description: '智能评分解释', consumers: ['IntelligentScorePage', 'TrendAndExplanation', 'ScoreDocPage'] },
  { name: 'MultiFactorFilterPanel', level: 'organism', sourcePath: 'src/components/organisms/analysis/screening/MultiFactorFilterPanel.tsx', targetPath: 'src/components/organisms/analysis/screening/MultiFactorFilterPanel.tsx', status: 'active', description: '多因子筛选面板', consumers: ['MultiFactorFilterPage', 'SectorAnalysisPage', 'StockSearch'] },
  { name: 'SectorRotationHeatmap', level: 'organism', sourcePath: 'src/components/organisms/analysis/sector/SectorRotationHeatmap.tsx', targetPath: 'src/components/organisms/analysis/sector/SectorRotationHeatmap.tsx', status: 'active', description: '行业轮动热力图', consumers: ['SectorAnalysisPage', 'IndustryDashboardPage', 'HotSectorPage'] },
  { name: 'SignalQualityTrendChart', level: 'organism', sourcePath: 'src/components/organisms/analysis/signal/SignalQualityTrendChart.tsx', targetPath: 'src/components/organisms/analysis/signal/SignalQualityTrendChart.tsx', status: 'active', description: '信号质量趋势图', consumers: ['SignalQualityDashboardWidget', 'TradingFlowPage', 'StrategySnapshotPage'] },

  // --- News 域 ---
  { name: 'NewsFilterPanel', level: 'organism', sourcePath: 'src/components/organisms/news/NewsFilterPanel.tsx', targetPath: 'src/components/organisms/news/NewsFilterPanel.tsx', status: 'active', description: '资讯筛选面板', consumers: ['NewsPage', 'HotSectorPage'] },
  { name: 'NewsCard', level: 'organism', sourcePath: 'src/components/organisms/news/NewsCard.tsx', targetPath: 'src/components/organisms/news/NewsCard.tsx', status: 'active', description: '资讯卡片', consumers: ['NewsPage', 'SearchResultList', 'HotSectorPage'] },
  { name: 'NewsSentimentTrend', level: 'organism', sourcePath: 'src/components/organisms/analysis/news/NewsSentimentTrend.tsx', targetPath: 'src/components/organisms/analysis/news/NewsSentimentTrend.tsx', status: 'active', description: '资讯情绪趋势', consumers: ['NewsPage', 'SectorAnalysisPage', 'HotSectorPage'] },

  // --- Trading 域 ---
  { name: 'RiskControlPanel', level: 'organism', sourcePath: 'src/components/organisms/trading/RiskControlPanel.tsx', targetPath: 'src/components/organisms/trading/RiskControlPanel.tsx', status: 'active', description: '风控面板', consumers: ['TradingFlowPage', 'RiskControlPage', 'PortfolioPage'] },
  { name: 'OrderExecutionPanel', level: 'organism', sourcePath: 'src/components/organisms/trading/OrderExecutionPanel.tsx', targetPath: 'src/components/organisms/trading/OrderExecutionPanel.tsx', status: 'active', description: '订单执行面板', consumers: ['TradingFlowPage', 'HoldingsPage'] },
  { name: 'TradingSignalPanel', level: 'organism', sourcePath: 'src/components/organisms/trading/TradingSignalPanel.tsx', targetPath: 'src/components/organisms/trading/TradingSignalPanel.tsx', status: 'active', description: '交易信号面板', consumers: ['TradingFlowPage', 'StrategySnapshotPage', 'SignalSpectrum'] },

  // --- Output 域 ---
  { name: 'ReviewWizard', level: 'organism', sourcePath: 'src/components/organisms/output/ReviewWizard.tsx', targetPath: 'src/components/organisms/output/ReviewWizard.tsx', status: 'active', description: '复盘向导', consumers: ['ReviewWizardPage', 'OutputApp', 'TradeReviewPage'] },
  { name: 'ReviewArtifactCard', level: 'organism', sourcePath: 'src/components/organisms/output/ReviewArtifactCard.tsx', targetPath: 'src/components/organisms/output/ReviewArtifactCard.tsx', status: 'active', description: '复盘产物卡片', consumers: ['TradeReviewPage', 'ReviewWizard', 'OutputHubPage'] },
  { name: 'ReviewArtifactModal', level: 'organism', sourcePath: 'src/components/organisms/output/ReviewArtifactModal.tsx', targetPath: 'src/components/organisms/output/ReviewArtifactModal.tsx', status: 'active', description: '复盘产物弹窗', consumers: ['ReviewArtifactCard', 'ReviewWizard', 'TradeReviewPage'] },
  { name: 'reviewArtifact', level: 'organism', sourcePath: 'src/components/organisms/output/reviewArtifact.ts', targetPath: 'src/components/organisms/output/reviewArtifact.ts', status: 'active', description: '复盘产物类型与工具', consumers: ['ReviewWizard', 'ReviewArtifactCard', 'TradeReviewPage'] },
  { name: 'BuySellPointReviewPanel', level: 'organism', sourcePath: 'src/components/organisms/output/BuySellPointReviewPanel.tsx', targetPath: 'src/components/organisms/output/BuySellPointReviewPanel.tsx', status: 'active', description: '买卖点复盘面板', consumers: ['TradeReviewPage', 'ReviewWizard'] },
  { name: 'CycleRetrospectiveView', level: 'organism', sourcePath: 'src/components/organisms/output/CycleRetrospectiveView.tsx', targetPath: 'src/components/organisms/output/CycleRetrospectiveView.tsx', status: 'active', description: '周期回顾视图', consumers: ['RetrospectivePage', 'OutputHubPage'] },
  { name: 'CycleRetrospectivePanel', level: 'organism', sourcePath: 'src/components/organisms/output/prediction/CycleRetrospectivePanel.tsx', targetPath: 'src/components/organisms/output/prediction/CycleRetrospectivePanel.tsx', status: 'active', description: '周期回顾面板', consumers: ['RetrospectivePage', 'OutputHubPage', 'TradeReviewPage'] },
  { name: 'FactorDashboardPanel', level: 'organism', sourcePath: 'src/components/organisms/output/prediction/FactorDashboardPanel.tsx', targetPath: 'src/components/organisms/output/prediction/FactorDashboardPanel.tsx', status: 'active', description: '因子仪表盘面板', consumers: ['FactorDashboardPage', 'OutputHubPage', 'MultiFactorFilterPage'] },
  { name: 'PredictionPanel', level: 'organism', sourcePath: 'src/components/organisms/output/prediction/PredictionPanel.tsx', targetPath: 'src/components/organisms/output/prediction/PredictionPanel.tsx', status: 'active', description: '预测面板', consumers: ['PredictionPage', 'OutputHubPage', 'TradeReviewPage'] },

  // --- System 域 ---
  { name: 'AgentHealthCard', level: 'organism', sourcePath: 'src/components/organisms/system/AgentHealthCard.tsx', targetPath: 'src/components/organisms/system/AgentHealthCard.tsx', status: 'active', description: 'Agent 健康卡片', consumers: ['SystemMonitorPage', 'AgentPerformanceWidget', 'AgentHubPage'] },
  { name: 'EngineStatusCard', level: 'organism', sourcePath: 'src/components/organisms/system/EngineStatusCard.tsx', targetPath: 'src/components/organisms/system/EngineStatusCard.tsx', status: 'active', description: '引擎状态卡片', consumers: ['SystemMonitorPage', 'EngineStatusWidget', 'HealthDashboardPage'] },
  { name: 'MigrationPanel', level: 'organism', sourcePath: 'src/components/organisms/system/MigrationPanel.tsx', targetPath: 'src/components/organisms/system/MigrationPanel.tsx', status: 'active', description: '迁移面板', consumers: ['SystemMonitorPage', 'MCPServerDashboardPage'] },
  { name: 'AgentTaskList', level: 'organism', sourcePath: 'src/components/organisms/system/AgentTaskList.tsx', targetPath: 'src/components/organisms/system/AgentTaskList.tsx', status: 'active', description: 'Agent 任务列表', consumers: ['AgentTasksPage', 'AgentDetailPage', 'SystemMonitorPage'] },
  { name: 'LogStreamPanel', level: 'organism', sourcePath: 'src/components/organisms/system/LogStreamPanel.tsx', targetPath: 'src/components/organisms/system/LogStreamPanel.tsx', status: 'active', description: '日志流面板', consumers: ['SystemMonitorPage', 'LiveLogStream', 'DataTestPanel'] },
  { name: 'SystemArchitectureDiagram', level: 'organism', sourcePath: 'src/components/organisms/system/SystemArchitectureDiagram.tsx', targetPath: 'src/components/organisms/system/SystemArchitectureDiagram.tsx', status: 'active', description: '系统架构图', consumers: ['SystemArchitectureWidget', 'SystemMonitorPage', 'HealthDashboardPage'] },
  { name: 'MigrationPreviewTab', level: 'organism', sourcePath: 'src/components/organisms/system/migration/MigrationPreviewTab.tsx', targetPath: 'src/components/organisms/system/migration/MigrationPreviewTab.tsx', status: 'active', description: '迁移预览 Tab', consumers: ['MigrationPanel', 'MCPServerDashboardPage'] },
  { name: 'MigrationReportTab', level: 'organism', sourcePath: 'src/components/organisms/system/migration/MigrationReportTab.tsx', targetPath: 'src/components/organisms/system/migration/MigrationReportTab.tsx', status: 'active', description: '迁移报告 Tab', consumers: ['MigrationPanel', 'MCPServerDashboardPage'] },
  { name: 'MigrationUploadTab', level: 'organism', sourcePath: 'src/components/organisms/system/migration/MigrationUploadTab.tsx', targetPath: 'src/components/organisms/system/migration/MigrationUploadTab.tsx', status: 'active', description: '迁移上传 Tab', consumers: ['MigrationPanel', 'MCPServerDashboardPage'] },
  { name: 'migrationUtils', level: 'organism', sourcePath: 'src/components/organisms/system/migration/migrationUtils.ts', targetPath: 'src/components/organisms/system/migration/migrationUtils.ts', status: 'active', description: '迁移工具函数', consumers: ['MigrationPanel', 'MigrationPreviewTab', 'MigrationReportTab'] },
  { name: 'useMcpMigration', level: 'organism', sourcePath: 'src/components/organisms/system/migration/useMcpMigration.ts', targetPath: 'src/components/organisms/system/migration/useMcpMigration.ts', status: 'active', description: 'MCP 迁移 Hook', consumers: ['MigrationPanel', 'MigrationUploadTab'] },
  { name: 'OrchestratorStatusPanel', level: 'organism', sourcePath: 'src/components/organisms/system/OrchestratorStatusPanel.tsx', targetPath: 'src/components/organisms/system/OrchestratorStatusPanel.tsx', status: 'active', description: '编排器状态面板', consumers: ['SystemMonitorPage', 'HealthDashboardPage'] },

  // --- Agent 域 ---
  { name: 'GenericAgentDetail', level: 'organism', sourcePath: 'src/components/organisms/agent/GenericAgentDetail.tsx', targetPath: 'src/components/organisms/agent/GenericAgentDetail.tsx', status: 'active', description: '通用 Agent 详情', consumers: ['AgentDetailPage', 'AgentHubPage', 'agentComponentRegistry'] },
  { name: 'V6ScoringAgentDetail', level: 'organism', sourcePath: 'src/components/organisms/agent/V6ScoringAgentDetail.tsx', targetPath: 'src/components/organisms/agent/V6ScoringAgentDetail.tsx', status: 'active', description: 'V6 评分 Agent 详情', consumers: ['AgentDetailPage', 'agentComponentRegistry', 'AgentHubPage'] },
  { name: 'agentComponentRegistry', level: 'organism', sourcePath: 'src/components/organisms/agent/agentComponentRegistry.ts', targetPath: 'src/components/organisms/agent/agentComponentRegistry.ts', status: 'active', description: 'Agent UI 组件注册表（agentId → 详情组件映射）', consumers: ['AgentDetailPage', 'GenericAgentDetail', 'V6ScoringAgentDetail'] },
  { name: 'StandardAgentDetail', level: 'organism', sourcePath: 'src/components/organisms/agent/StandardAgentDetail.tsx', targetPath: 'src/components/organisms/agent/StandardAgentDetail.tsx', status: 'active', description: '标准 Agent 详情', consumers: ['AgentDetailPage', 'AgentHubPage', 'agentComponentRegistry'] },

  // --- Strategy 域 ---
  { name: 'StrategyGroupCard', level: 'organism', sourcePath: 'src/components/organisms/strategy/StrategyGroupCard.tsx', targetPath: 'src/components/organisms/strategy/StrategyGroupCard.tsx', status: 'active', description: '策略组卡片', consumers: ['StrategySnapshotPage', 'HotSectorPage'] },
  { name: 'ChangeLogPanel', level: 'organism', sourcePath: 'src/components/organisms/strategy/ChangeLogPanel.tsx', targetPath: 'src/components/organisms/strategy/ChangeLogPanel.tsx', status: 'active', description: '变更日志面板', consumers: ['StrategySnapshotPage', 'ChangelogPage'] },

  // --- LocalDoc 域 ---
  { name: 'LocalDocCard', level: 'organism', sourcePath: 'src/components/organisms/localDoc/LocalDocCard.tsx', targetPath: 'src/components/organisms/localDoc/LocalDocCard.tsx', status: 'active', description: '本地文档卡片', consumers: ['LocalKnowledgePage', 'ScoreDocPage'] },

  // --- ScoreDoc 域 ---
  { name: 'ScoreDocVersionTable', level: 'organism', sourcePath: 'src/components/organisms/scoreDoc/ScoreDocVersionTable.tsx', targetPath: 'src/components/organisms/scoreDoc/ScoreDocVersionTable.tsx', status: 'active', description: '评分文档版本表', consumers: ['ScoreDocPage', 'scoreDocArchiveService'] },

  // --- Widget 域 ---
  { name: 'WidgetShell', level: 'organism', sourcePath: 'src/components/widgets/WidgetShell.tsx', targetPath: 'src/components/widgets/WidgetShell.tsx', status: 'active', description: 'Widget 外壳', consumers: ['CockpitLayout', 'widgetRegistry', '全 Cockpit Widget'] },

  // --- Cabin 域 ---
  { name: 'IndustryHistoryCard', level: 'organism', sourcePath: 'src/components/cabin/IndustryHistoryCard.tsx', targetPath: 'src/components/cabin/IndustryHistoryCard.tsx', status: 'active', description: '行业历史卡片', consumers: ['IndustryScorePage', 'ScoreHistoryPanel', 'IntelligentScorePage'] },
  { name: 'IndustrySkillSnapshotCard', level: 'organism', sourcePath: 'src/components/cabin/IndustrySkillSnapshotCard.tsx', targetPath: 'src/components/cabin/IndustrySkillSnapshotCard.tsx', status: 'active', description: '行业技能快照卡', consumers: ['IndustryScorePage', 'IndustryDashboardPage'] },
  { name: 'ScoreSnapshot', level: 'organism', sourcePath: 'src/components/cabin/ScoreSnapshot.tsx', targetPath: 'src/components/cabin/ScoreSnapshot.tsx', status: 'active', description: '评分快照', consumers: ['IntelligentScorePage', 'IndustryScorePage', 'ScoreSummary'] },
  { name: 'ScoreSummary', level: 'organism', sourcePath: 'src/components/cabin/ScoreSummary.tsx', targetPath: 'src/components/cabin/ScoreSummary.tsx', status: 'active', description: '评分汇总', consumers: ['IntelligentScorePage', 'IndustryScorePage', 'ScoreSnapshot'] },
  { name: 'ScoreHistoryTable', level: 'organism', sourcePath: 'src/components/cabin/ScoreHistoryTable.tsx', targetPath: 'src/components/cabin/ScoreHistoryTable.tsx', status: 'active', description: '评分历史表', consumers: ['ScoreHistoryPanel', 'IntelligentScorePage', 'ScoreDocPage'] },
  { name: 'ScoreItem', level: 'organism', sourcePath: 'src/components/cabin/ScoreItem.tsx', targetPath: 'src/components/cabin/ScoreItem.tsx', status: 'active', description: '评分项', consumers: ['ScoreSummary', 'ScoreSnapshot', 'IntelligentScoreBasisCard'] },
  { name: 'IntelligentScoreBasisCard', level: 'organism', sourcePath: 'src/components/cabin/IntelligentScoreBasisCard.tsx', targetPath: 'src/components/cabin/IntelligentScoreBasisCard.tsx', status: 'active', description: '智能评分依据卡', consumers: ['IntelligentScorePage', 'ScoreDocPage', 'TrendAndExplanation'] },

  // --- Chart 域 ---
  { name: 'LineChart', level: 'organism', sourcePath: 'src/components/chart/LineChart.tsx', targetPath: 'src/components/chart/LineChart.tsx', status: 'active', description: '折线图', consumers: ['MultiPeriodTrendChart', 'NewsSentimentTrend', 'SignalQualityTrendChart'] },
  { name: 'BarChart', level: 'organism', sourcePath: 'src/components/chart/BarChart.tsx', targetPath: 'src/components/chart/BarChart.tsx', status: 'active', description: '柱状图', consumers: ['ScoreFactorWaterfall', 'SubIndicatorBar', 'ScoreDistribution'] },
  { name: 'AreaChart', level: 'organism', sourcePath: 'src/components/chart/AreaChart.tsx', targetPath: 'src/components/chart/AreaChart.tsx', status: 'active', description: '面积图', consumers: ['NewsSentimentTrend', 'TrendLineChart', 'SignalQualityTrendChart'] },
  { name: 'CandlestickChart', level: 'organism', sourcePath: 'src/components/chart/CandlestickChart.tsx', targetPath: 'src/components/chart/CandlestickChart.tsx', status: 'active', description: 'K线图', consumers: ['TradingFlowPage', 'BacktestPage', 'PnLAnalysisWidget'] },
  { name: 'MultiPaneChart', level: 'organism', sourcePath: 'src/components/chart/MultiPaneChart.tsx', targetPath: 'src/components/chart/MultiPaneChart.tsx', status: 'active', description: '多窗格图表', consumers: ['TradingFlowPage', 'StockDetailPage', 'BacktestPage'] },
  { name: 'GaugeChart', level: 'organism', sourcePath: 'src/components/chart/GaugeChart.tsx', targetPath: 'src/components/chart/GaugeChart.tsx', status: 'active', description: '仪表盘图', consumers: ['RiskControlPanel', 'QualityIndicator', 'ScoreSnapshot'] },
  { name: 'ScoreRadar', level: 'organism', sourcePath: 'src/components/chart/ScoreRadar.tsx', targetPath: 'src/components/chart/ScoreRadar.tsx', status: 'active', description: '评分雷达图', consumers: ['IntelligentScorePage', 'IndustryScorePage', 'ScoreSummary'] },
  { name: 'FactorHeatmap', level: 'organism', sourcePath: 'src/components/chart/FactorHeatmap.tsx', targetPath: 'src/components/chart/FactorHeatmap.tsx', status: 'active', description: '因子热力图', consumers: ['MultiFactorFilterPanel', 'ScoreFactorWaterfall', 'FactorDashboardPanel'] },
  { name: 'ChipDistributionChart', level: 'organism', sourcePath: 'src/components/chart/ChipDistributionChart.tsx', targetPath: 'src/components/chart/ChipDistributionChart.tsx', status: 'active', description: '筹码分布图（CYQ 模型）', consumers: ['TradingFlowPage', 'StockDetailPage'] },
  { name: 'IndustryHeatmap', level: 'organism', sourcePath: 'src/components/chart/industry/IndustryHeatmap.tsx', targetPath: 'src/components/chart/industry/IndustryHeatmap.tsx', status: 'active', description: '行业热力图', consumers: ['IndustryDashboardPage', 'SectorAnalysisPage', 'HotSectorPage'] },
  { name: 'IndustryV4Panel', level: 'organism', sourcePath: 'src/components/chart/industry/IndustryV4Panel.tsx', targetPath: 'src/components/chart/industry/IndustryV4Panel.tsx', status: 'active', description: '行业 V4 综合面板', consumers: ['TBD - pending integration'] },
  { name: 'IndustryV4Radar', level: 'organism', sourcePath: 'src/components/chart/industry/IndustryV4Radar.tsx', targetPath: 'src/components/chart/industry/IndustryV4Radar.tsx', status: 'active', description: '行业 V4 雷达图', consumers: ['TBD - pending integration'] },
  { name: 'SubIndicatorBar', level: 'organism', sourcePath: 'src/components/chart/industry/SubIndicatorBar.tsx', targetPath: 'src/components/chart/industry/SubIndicatorBar.tsx', status: 'active', description: '行业子指标柱状图', consumers: ['TBD - pending integration'] },
  { name: 'TrendLineChart', level: 'organism', sourcePath: 'src/components/chart/industry/TrendLineChart.tsx', targetPath: 'src/components/chart/industry/TrendLineChart.tsx', status: 'active', description: '行业趋势折线图', consumers: ['TBD - pending integration'] },
  { name: 'ValuationDistribution', level: 'organism', sourcePath: 'src/components/chart/industry/ValuationDistribution.tsx', targetPath: 'src/components/chart/industry/ValuationDistribution.tsx', status: 'active', description: '行业估值分布图', consumers: ['TBD - pending integration'] },

  // --- Input 域 ---
  { name: 'CollectionPlanPanel', level: 'organism', sourcePath: 'src/components/organisms/input/CollectionPlanPanel.tsx', targetPath: 'src/components/organisms/input/CollectionPlanPanel.tsx', status: 'active', description: '采集计划面板', consumers: ['CollectTaskPage', 'InputDashboard', 'SevenDimConfigPage'] },
  { name: 'DataCollectionWizard', level: 'organism', sourcePath: 'src/components/organisms/input/DataCollectionWizard.tsx', targetPath: 'src/components/organisms/input/DataCollectionWizard.tsx', status: 'active', description: '采集向导', consumers: ['CollectTaskPage', 'InputDashboard', 'FetcherConfigPage'] },
  { name: 'TraceReplayPanel', level: 'organism', sourcePath: 'src/components/organisms/input/TraceReplayPanel.tsx', targetPath: 'src/components/organisms/input/TraceReplayPanel.tsx', status: 'active', description: 'Trace 回放面板', consumers: ['DataTestPanel', 'CollectTaskPage'] },
  { name: 'QualityIndicator', level: 'organism', sourcePath: 'src/components/organisms/input/QualityIndicator.tsx', targetPath: 'src/components/organisms/input/QualityIndicator.tsx', status: 'active', description: '质量指示器', consumers: ['CollectTaskPage', 'InputDashboard', 'DataTestPanel'] },
  { name: 'StockSearch', level: 'organism', sourcePath: 'src/components/organisms/input/StockSearch.tsx', targetPath: 'src/components/organisms/input/StockSearch.tsx', status: 'active', description: '股票搜索', consumers: ['PoolBoardPage', 'CollectTaskPage', 'InputApp'] },
  { name: 'LiveLogStream', level: 'organism', sourcePath: 'src/components/organisms/input/LiveLogStream.tsx', targetPath: 'src/components/organisms/input/LiveLogStream.tsx', status: 'active', description: '实时日志流', consumers: ['CollectTaskPage', 'DataTestPanel', 'LogStreamPanel'] },
  { name: 'SourcePrioritySelect', level: 'organism', sourcePath: 'src/components/organisms/input/SourcePrioritySelect.tsx', targetPath: 'src/components/organisms/input/SourcePrioritySelect.tsx', status: 'active', description: '数据源优先级选择', consumers: ['SevenDimConfigPage', 'FetcherConfigPage', 'DataCollectionWizard'] },
  { name: 'FieldSelector', level: 'organism', sourcePath: 'src/components/organisms/input/FieldSelector.tsx', targetPath: 'src/components/organisms/input/FieldSelector.tsx', status: 'active', description: '字段选择器', consumers: ['SevenDimConfigPage', 'MultiFactorFilterPanel', 'DataCollectionWizard'] },
  { name: 'PolicyForm', level: 'organism', sourcePath: 'src/components/organisms/input/PolicyForm.tsx', targetPath: 'src/components/organisms/input/PolicyForm.tsx', status: 'active', description: '策略表单', consumers: ['SevenDimConfigPage', 'FetcherConfigPage', 'DimensionConfigCard'] },
  { name: 'DimensionConfigCard', level: 'organism', sourcePath: 'src/components/organisms/input/DimensionConfigCard.tsx', targetPath: 'src/components/organisms/input/DimensionConfigCard.tsx', status: 'active', description: '维度配置卡', consumers: ['SevenDimConfigPage', 'DataCollectionWizard'] },
  { name: 'CollectionTimeline', level: 'organism', sourcePath: 'src/components/organisms/input/CollectionTimeline.tsx', targetPath: 'src/components/organisms/input/CollectionTimeline.tsx', status: 'active', description: '采集时间线', consumers: ['CollectTaskPage', 'InputDashboard'] },
  { name: 'CollectionSwimlane', level: 'organism', sourcePath: 'src/components/organisms/input/CollectionSwimlane.tsx', targetPath: 'src/components/organisms/input/CollectionSwimlane.tsx', status: 'active', description: '采集泳道图', consumers: ['CollectTaskPage', 'SevenDimConfigPage'] },
  { name: 'QuotaEstimatePanel', level: 'organism', sourcePath: 'src/components/organisms/input/QuotaEstimatePanel.tsx', targetPath: 'src/components/organisms/input/QuotaEstimatePanel.tsx', status: 'active', description: '配额估算面板', consumers: ['CollectTaskPage', 'SevenDimConfigPage'] },
  { name: 'ApiTestDialog', level: 'organism', sourcePath: 'src/components/organisms/input/ApiTestDialog.tsx', targetPath: 'src/components/organisms/input/ApiTestDialog.tsx', status: 'active', description: 'API 测试弹窗', consumers: ['DataTestPanel', 'FetcherConfigPage', 'SevenDimConfigPage'] },
  { name: 'CollectionStrategyStep', level: 'organism', sourcePath: 'src/components/organisms/input/wizard-steps/CollectionStrategyStep.tsx', targetPath: 'src/components/organisms/input/wizard-steps/CollectionStrategyStep.tsx', status: 'active', description: '采集向导-策略步骤', consumers: ['DataCollectionWizard'] },
  { name: 'DataSourceConfigStep', level: 'organism', sourcePath: 'src/components/organisms/input/wizard-steps/DataSourceConfigStep.tsx', targetPath: 'src/components/organisms/input/wizard-steps/DataSourceConfigStep.tsx', status: 'active', description: '采集向导-数据源配置步骤', consumers: ['DataCollectionWizard'] },
  { name: 'ExecutionMonitorStep', level: 'organism', sourcePath: 'src/components/organisms/input/wizard-steps/ExecutionMonitorStep.tsx', targetPath: 'src/components/organisms/input/wizard-steps/ExecutionMonitorStep.tsx', status: 'active', description: '采集向导-执行监控步骤', consumers: ['DataCollectionWizard'] },
  { name: 'TaskPreviewStep', level: 'organism', sourcePath: 'src/components/organisms/input/wizard-steps/TaskPreviewStep.tsx', targetPath: 'src/components/organisms/input/wizard-steps/TaskPreviewStep.tsx', status: 'active', description: '采集向导-任务预览步骤', consumers: ['DataCollectionWizard'] },
  { name: 'InputFlowErrorBoundary', level: 'organism', sourcePath: 'src/components/organisms/input/InputFlowErrorBoundary.tsx', targetPath: 'src/components/organisms/input/InputFlowErrorBoundary.tsx', status: 'active', description: '输入流错误边界', consumers: ['InputApp', 'CollectTaskPage'] },

  // --- Shared 域 ---
  { name: 'ErrorBoundary', level: 'organism', sourcePath: 'src/components/organisms/shared/ErrorBoundary.tsx', targetPath: 'src/components/organisms/shared/ErrorBoundary.tsx', status: 'active', description: '错误边界', consumers: ['App.tsx', 'main.tsx', 'RouteErrorBoundary'] },
  { name: 'RouteErrorBoundary', level: 'organism', sourcePath: 'src/components/organisms/shared/RouteErrorBoundary.tsx', targetPath: 'src/components/organisms/shared/RouteErrorBoundary.tsx', status: 'active', description: '路由错误边界', consumers: ['全路由页面', 'App.tsx', 'OutputApp'] },
  { name: 'WidgetErrorBoundary', level: 'organism', sourcePath: 'src/components/organisms/shared/WidgetErrorBoundary.tsx', targetPath: 'src/components/organisms/shared/WidgetErrorBoundary.tsx', status: 'active', description: 'Widget 错误边界', consumers: ['WidgetShell', 'CockpitShell', '全 Cockpit Widget'] },
  { name: 'PageSkeleton', level: 'organism', sourcePath: 'src/components/organisms/shared/PageSkeleton.tsx', targetPath: 'src/components/organisms/shared/PageSkeleton.tsx', status: 'active', description: '页面骨架屏', consumers: ['全页面通用', 'SidebarLayout', 'DashboardLayout'] },
  { name: 'installGlobalErrorHandler', level: 'organism', sourcePath: 'src/components/organisms/shared/installGlobalErrorHandler.ts', targetPath: 'src/components/organisms/shared/installGlobalErrorHandler.ts', status: 'active', description: '全局错误监听安装函数（非 UI 组件，基础设施）', consumers: ['main.tsx', 'App.tsx', 'CockpitShell'] },
  { name: 'ScoreFactorDeltaPanel', level: 'organism', sourcePath: 'src/components/organisms/shared/ScoreFactorDeltaPanel.tsx', targetPath: 'src/components/organisms/shared/ScoreFactorDeltaPanel.tsx', status: 'active', description: '评分因子差异面板', consumers: ['IntelligentScorePage', 'IndustryScorePage', 'ScoreResultCard'] },
  { name: 'ScoreUpdateAlert', level: 'organism', sourcePath: 'src/components/organisms/shared/ScoreUpdateAlert.tsx', targetPath: 'src/components/organisms/shared/ScoreUpdateAlert.tsx', status: 'active', description: '评分更新提醒', consumers: ['IntelligentScorePage', 'IndustryScorePage', 'ScoreDocPage'] },
  { name: 'LLMConfigWidget', level: 'organism', sourcePath: 'src/components/organisms/shared/LLMConfigWidget.tsx', targetPath: 'src/components/organisms/shared/LLMConfigWidget.tsx', status: 'active', description: 'LLM 配置 Widget', consumers: ['ConfigApp', 'ApiConfigurationPage', 'LlmManagementPage'] },
  { name: 'MemoryModeBanner', level: 'organism', sourcePath: 'src/components/organisms/shared/MemoryModeBanner.tsx', targetPath: 'src/components/organisms/shared/MemoryModeBanner.tsx', status: 'active', description: '记忆模式横幅', consumers: ['SidebarLayout', 'DashboardLayout'] },

  // --- Cockpit 域 ---
  { name: 'SignalSpectrum', level: 'organism', sourcePath: 'src/components/cockpit/SignalSpectrum.tsx', targetPath: 'src/components/cockpit/SignalSpectrum.tsx', status: 'active', description: '信号频谱（cockpit 域，仅 registry 标注不物理搬）', consumers: ['PortalShell', 'CockpitShell', 'TradingSignalPanel'] },
  { name: 'DensityContext', level: 'organism', sourcePath: 'src/components/cockpit/DensityContext.tsx', targetPath: 'src/components/cockpit/DensityContext.tsx', status: 'active', description: '信息密度 Context', consumers: ['PortalShell', 'CockpitShell', 'DensityToggle'] },
  { name: 'DensityToggle', level: 'organism', sourcePath: 'src/components/cockpit/DensityToggle.tsx', targetPath: 'src/components/cockpit/DensityToggle.tsx', status: 'active', description: '信息密度切换', consumers: ['PortalShell', 'CockpitShell', 'PageHeader'] },
  { name: 'SecurityStatus', level: 'organism', sourcePath: 'src/components/cockpit/SecurityStatus.tsx', targetPath: 'src/components/cockpit/SecurityStatus.tsx', status: 'active', description: '安全状态', consumers: ['PortalShell', 'CockpitShell', 'HealthDashboardPage'] },
]
