$docsRoot = Join-Path (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent) 'docs'

$migrations = @(
    @{ Source = "$docsRoot\00-meta\DIRECTORY_STRUCTURE_GUIDE.md"; Target = "$docsRoot\1-nav-governance\a1-index-constitution\DIRECTORY_STRUCTURE_GUIDE.md" }
    @{ Source = "$docsRoot\00-meta\GOVERNANCE.md"; Target = "$docsRoot\1-nav-governance\a1-index-constitution\GOVERNANCE.md" }
    @{ Source = "$docsRoot\00-meta\REGISTRY_INDEX.md"; Target = "$docsRoot\1-nav-governance\a1-index-constitution\REGISTRY_INDEX.md" }
    @{ Source = "$docsRoot\00-meta\CLEANUP_SCHEDULE.md"; Target = "$docsRoot\1-nav-governance\a1-index-constitution\CLEANUP_SCHEDULE.md" }
    @{ Source = "$docsRoot\00-meta\文档体系体检报告-v9.md"; Target = "$docsRoot\1-nav-governance\a1-index-constitution\文档体系体检报告-v9.md" }
    @{ Source = "$docsRoot\00-meta\文档归类体系结构.md"; Target = "$docsRoot\1-nav-governance\a1-index-constitution\文档归类体系结构.md" }
    @{ Source = "$docsRoot\00-meta\V9-项目健康状态总览.md"; Target = "$docsRoot\1-nav-governance\a1-index-constitution\V9-项目健康状态总览.md" }
    @{ Source = "$docsRoot\00-meta\V9-文档治理修复行动计划.md"; Target = "$docsRoot\1-nav-governance\a1-index-constitution\V9-文档治理修复行动计划.md" }
    @{ Source = "$docsRoot\00-meta\文档管理系统评分报告.md"; Target = "$docsRoot\1-nav-governance\a1-index-constitution\文档管理系统评分报告.md" }
    @{ Source = "$docsRoot\00-meta\月度文档体检检查清单.md"; Target = "$docsRoot\1-nav-governance\a1-index-constitution\月度文档体检检查清单.md" }
    @{ Source = "$docsRoot\01-requirements\01-vision-and-goals.md"; Target = "$docsRoot\1-nav-governance\a2-requirements\01-vision-and-goals.md" }
    @{ Source = "$docsRoot\01-requirements\02-functional-specs.md"; Target = "$docsRoot\1-nav-governance\a2-requirements\02-functional-specs.md" }
    @{ Source = "$docsRoot\01-requirements\03-architecture-standards.md"; Target = "$docsRoot\1-nav-governance\a2-requirements\03-architecture-standards.md" }
    @{ Source = "$docsRoot\01-requirements\v9-system-blueprint.md"; Target = "$docsRoot\1-nav-governance\a2-requirements\v9-system-blueprint.md" }
    @{ Source = "$docsRoot\01-requirements\V9数据宪法.md"; Target = "$docsRoot\1-nav-governance\a2-requirements\V9数据宪法.md" }
    @{ Source = "$docsRoot\03-development\plugins\*.md"; Target = "$docsRoot\1-nav-governance\a3-plugins\" }
    @{ Source = "$docsRoot\02-design\architecture\overview.md"; Target = "$docsRoot\2-architecture\b1-overview\overview.md" }
    @{ Source = "$docsRoot\02-design\architecture\cabins-overview.md"; Target = "$docsRoot\2-architecture\b1-overview\cabins-overview.md" }
    @{ Source = "$docsRoot\02-design\architecture\services-catalog.md"; Target = "$docsRoot\2-architecture\b1-overview\services-catalog.md" }
    @{ Source = "$docsRoot\02-design\architecture\security-model.md"; Target = "$docsRoot\2-architecture\b1-overview\security-model.md" }
    @{ Source = "$docsRoot\02-design\architecture\deployment.md"; Target = "$docsRoot\2-architecture\b1-overview\deployment.md" }
    @{ Source = "$docsRoot\02-design\architecture\architecture-version-comparison.md"; Target = "$docsRoot\2-architecture\b1-overview\architecture-version-comparison.md" }
    @{ Source = "$docsRoot\02-design\architecture\v10-architecture-alignment.md"; Target = "$docsRoot\2-architecture\b1-overview\v10-architecture-alignment.md" }
    @{ Source = "$docsRoot\02-design\ARCHITECTURE.md"; Target = "$docsRoot\2-architecture\b2-subsystems\ARCHITECTURE.md" }
    @{ Source = "$docsRoot\02-design\data-collection-architecture.md"; Target = "$docsRoot\2-architecture\b2-subsystems\data-collection-architecture.md" }
    @{ Source = "$docsRoot\02-design\modules\data-layer-overview.md"; Target = "$docsRoot\2-architecture\b2-subsystems\data-layer-overview.md" }
    @{ Source = "$docsRoot\02-design\mcp-coupling-analysis-report.md"; Target = "$docsRoot\2-architecture\b2-subsystems\mcp-coupling-analysis-report.md" }
    @{ Source = "$docsRoot\02-design\architecture\adr\*.md"; Target = "$docsRoot\2-architecture\b3-adr\" }
    @{ Source = "$docsRoot\01-requirements\adr\*.md"; Target = "$docsRoot\2-architecture\b3-adr\" }
    @{ Source = "$docsRoot\02-design\ADR\*.md"; Target = "$docsRoot\2-architecture\b3-adr\" }
    @{ Source = "$docsRoot\02-design\architecture-compliance-report.md"; Target = "$docsRoot\2-architecture\b4-compliance\architecture-compliance-report.md" }
    @{ Source = "$docsRoot\02-design\v9-architecture-rectification-strategy.md"; Target = "$docsRoot\2-architecture\b4-compliance\v9-architecture-rectification-strategy.md" }
    @{ Source = "$docsRoot\02-design\v6-v9-architecture-audit-plan.md"; Target = "$docsRoot\2-architecture\b4-compliance\v6-v9-architecture-audit-plan.md" }
    @{ Source = "$docsRoot\02-design\v6-v9-architecture-audit-action-list.md"; Target = "$docsRoot\2-architecture\b4-compliance\v6-v9-architecture-audit-action-list.md" }
    @{ Source = "$docsRoot\02-design\v6-v9-rectification-feasibility-report.md"; Target = "$docsRoot\2-architecture\b4-compliance\v6-v9-rectification-feasibility-report.md" }
    @{ Source = "$docsRoot\05-deployment\RELEASE_NOTES.md"; Target = "$docsRoot\2-architecture\b5-release\RELEASE_NOTES.md" }
    @{ Source = "$docsRoot\05-deployment\PR_DESCRIPTION.md"; Target = "$docsRoot\2-architecture\b5-release\PR_DESCRIPTION.md" }
    @{ Source = "$docsRoot\02-design\发布计划与评审_R01.md"; Target = "$docsRoot\2-architecture\b5-release\发布计划与评审_R01.md" }
    @{ Source = "$docsRoot\02-design\回滚方案与演练_R03.md"; Target = "$docsRoot\2-architecture\b5-release\回滚方案与演练_R03.md" }
    @{ Source = "$docsRoot\02-design\input-cabin-spec.md"; Target = "$docsRoot\3-functional-modules\c1-cabins\input-cabin-spec.md" }
    @{ Source = "$docsRoot\02-design\analysis-cabin-spec.md"; Target = "$docsRoot\3-functional-modules\c1-cabins\analysis-cabin-spec.md" }
    @{ Source = "$docsRoot\02-design\trading-cabin-spec.md"; Target = "$docsRoot\3-functional-modules\c1-cabins\trading-cabin-spec.md" }
    @{ Source = "$docsRoot\02-design\output-cabin-spec.md"; Target = "$docsRoot\3-functional-modules\c1-cabins\output-cabin-spec.md" }
    @{ Source = "$docsRoot\02-design\command-cabin-spec.md"; Target = "$docsRoot\3-functional-modules\c1-cabins\command-cabin-spec.md" }
    @{ Source = "$docsRoot\02-design\06-routing-specs.md"; Target = "$docsRoot\3-functional-modules\c1-cabins\06-routing-specs.md" }
    @{ Source = "$docsRoot\02-design\input-cabin-ui-reshaping.md"; Target = "$docsRoot\3-functional-modules\c1-cabins\input-cabin-ui-reshaping.md" }
    @{ Source = "$docsRoot\02-design\PAGE_STRUCTURE.md"; Target = "$docsRoot\3-functional-modules\c1-cabins\PAGE_STRUCTURE.md" }
    @{ Source = "$docsRoot\02-design\atomic-component-system.md"; Target = "$docsRoot\3-functional-modules\c2-components\atomic-component-system.md" }
    @{ Source = "$docsRoot\02-design\component-library-guide.md"; Target = "$docsRoot\3-functional-modules\c2-components\component-library-guide.md" }
    @{ Source = "$docsRoot\02-design\architecture\component-deprecation-policy.md"; Target = "$docsRoot\3-functional-modules\c2-components\component-deprecation-policy.md" }
    @{ Source = "$docsRoot\02-design\widget-development-guide.md"; Target = "$docsRoot\3-functional-modules\c3-cockpit\widget-development-guide.md" }
    @{ Source = "$docsRoot\02-design\widget-error-handling.md"; Target = "$docsRoot\3-functional-modules\c3-cockpit\widget-error-handling.md" }
    @{ Source = "$docsRoot\02-design\widget-integration-checklist.md"; Target = "$docsRoot\3-functional-modules\c3-cockpit\widget-integration-checklist.md" }
    @{ Source = "$docsRoot\02-design\cockpit\DATA_DEFINITION.md"; Target = "$docsRoot\3-functional-modules\c3-cockpit\DATA_DEFINITION.md" }
    @{ Source = "$docsRoot\02-design\v6-cockpit-ui-reference.md"; Target = "$docsRoot\3-functional-modules\c3-cockpit\v6-cockpit-ui-reference.md" }
    @{ Source = "$docsRoot\01-requirements\V9_L2状态层补齐路线图.md"; Target = "$docsRoot\3-functional-modules\c4-store\V9_L2状态层补齐路线图.md" }
    @{ Source = "$docsRoot\02-design\migration-news-useState-to-zustand.md"; Target = "$docsRoot\3-functional-modules\c4-store\migration-news-useState-to-zustand.md" }
    @{ Source = "$docsRoot\02-design\STATE_MANAGEMENT.md"; Target = "$docsRoot\3-functional-modules\c4-store\STATE_MANAGEMENT.md" }
    @{ Source = "$docsRoot\02-design\architecture\services\*.md"; Target = "$docsRoot\3-functional-modules\c5-services\" }
    @{ Source = "$docsRoot\02-design\V9_IndexedDB_Store_Schema.md"; Target = "$docsRoot\3-functional-modules\c6-data-layer\V9_IndexedDB_Store_Schema.md" }
    @{ Source = "$docsRoot\02-design\V9_数据血缘追踪.md"; Target = "$docsRoot\3-functional-modules\c6-data-layer\V9_数据血缘追踪.md" }
    @{ Source = "$docsRoot\02-design\data-collection-gap-analysis.md"; Target = "$docsRoot\3-functional-modules\c6-data-layer\data-collection-gap-analysis.md" }
    @{ Source = "$docsRoot\02-design\data-collection-route-ui-audit.md"; Target = "$docsRoot\3-functional-modules\c6-data-layer\data-collection-route-ui-audit.md" }
    @{ Source = "$docsRoot\02-design\data-flow-spec.md"; Target = "$docsRoot\3-functional-modules\c6-data-layer\data-flow-spec.md" }
    @{ Source = "$docsRoot\02-design\data-interaction-protocols.md"; Target = "$docsRoot\3-functional-modules\c6-data-layer\data-interaction-protocols.md" }
    @{ Source = "$docsRoot\02-design\DATA_DICTIONARY_INDEX.md"; Target = "$docsRoot\3-functional-modules\c7-data-dictionary\DATA_DICTIONARY_INDEX.md" }
    @{ Source = "$docsRoot\02-design\standards\DATA_DICTIONARY_INDEX.md"; Target = "$docsRoot\3-functional-modules\c7-data-dictionary\standards-DATA_DICTIONARY_INDEX.md" }
    @{ Source = "$docsRoot\02-design\standards\*.md"; Target = "$docsRoot\3-functional-modules\c7-data-dictionary\" }
    @{ Source = "$docsRoot\02-design\standards\DATA_DEFINITION.md"; Target = "$docsRoot\3-functional-modules\c7-data-dictionary\DATA_DEFINITION.md" }
    @{ Source = "$docsRoot\02-design\ai-center-data-definition.md"; Target = "$docsRoot\3-functional-modules\c7-data-dictionary\ai-center-data-definition.md" }
    @{ Source = "$docsRoot\02-design\blueprints\*.md"; Target = "$docsRoot\3-functional-modules\c7-data-dictionary\blueprints\" }
    @{ Source = "$docsRoot\03-development\v9-data-relationship-er.md"; Target = "$docsRoot\3-functional-modules\c7-data-dictionary\v9-data-relationship-er.md" }
    @{ Source = "$docsRoot\03-development\v9-data-timeline.md"; Target = "$docsRoot\3-functional-modules\c7-data-dictionary\v9-data-timeline.md" }
    @{ Source = "$docsRoot\02-design\《V9核心数据字典与类型定义（整合版）》.md"; Target = "$docsRoot\3-functional-modules\c7-data-dictionary\V9核心数据字典与类型定义整合版.md" }
    @{ Source = "$docsRoot\02-design\《V9现有数据资产清单》.md"; Target = "$docsRoot\3-functional-modules\c7-data-dictionary\V9现有数据资产清单.md" }
    @{ Source = "$docsRoot\02-design\《DataBridge端点与数据映射清单》.md"; Target = "$docsRoot\3-functional-modules\c7-data-dictionary\DataBridge端点与数据映射清单.md" }
    @{ Source = "$docsRoot\01-requirements\《DataBridge端点与数据映射清单》.md"; Target = "$docsRoot\3-functional-modules\c7-data-dictionary\DataBridge端点与数据映射清单-v2.md" }
    @{ Source = "$docsRoot\02-design\《功能模块数据契约》.md"; Target = "$docsRoot\3-functional-modules\c7-data-dictionary\功能模块数据契约.md" }
    @{ Source = "$docsRoot\02-design\design-tokens.md"; Target = "$docsRoot\4-technical-specs\d2-design-tokens\design-tokens.md" }
    @{ Source = "$docsRoot\02-design\design-token-mapping.md"; Target = "$docsRoot\4-technical-specs\d2-design-tokens\design-token-mapping.md" }
    @{ Source = "$docsRoot\02-design\spacing-tokens.md"; Target = "$docsRoot\4-technical-specs\d2-design-tokens\spacing-tokens.md" }
    @{ Source = "$docsRoot\02-design\token-usage-cookbook.md"; Target = "$docsRoot\4-technical-specs\d2-design-tokens\token-usage-cookbook.md" }
    @{ Source = "$docsRoot\02-design\song-aesthetics.md"; Target = "$docsRoot\4-technical-specs\d2-design-tokens\song-aesthetics.md" }
    @{ Source = "$docsRoot\02-design\ui-design-system.md"; Target = "$docsRoot\4-technical-specs\d2-design-tokens\ui-design-system.md" }
    @{ Source = "$docsRoot\02-design\04-ui-ux-specs.md"; Target = "$docsRoot\4-technical-specs\d2-design-tokens\04-ui-ux-specs.md" }
    @{ Source = "$docsRoot\03-development\complexity-governance.md"; Target = "$docsRoot\4-technical-specs\d3-quality-gates\complexity-governance.md" }
    @{ Source = "$docsRoot\03-development\quality-gates-baseline.md"; Target = "$docsRoot\4-technical-specs\d3-quality-gates\quality-gates-baseline.md" }
    @{ Source = "$docsRoot\02-design\09-quality-gates.md"; Target = "$docsRoot\4-technical-specs\d3-quality-gates\09-quality-gates.md" }
    @{ Source = "$docsRoot\03-development\performance-baseline.md"; Target = "$docsRoot\4-technical-specs\d3-quality-gates\performance-baseline.md" }
    @{ Source = "$docsRoot\03-development\development-workflow-sop.md"; Target = "$docsRoot\4-technical-specs\d3-quality-gates\development-workflow-sop.md" }
    @{ Source = "$docsRoot\03-development\jsdoc-convention.md"; Target = "$docsRoot\4-technical-specs\d4-documentation\jsdoc-convention.md" }
    @{ Source = "$docsRoot\02-design\00-README.md"; Target = "$docsRoot\4-technical-specs\d4-documentation\00-README.md" }
    @{ Source = "$docsRoot\03-development\code-review-guide.md"; Target = "$docsRoot\4-technical-specs\d4-documentation\code-review-guide.md" }
    @{ Source = "$docsRoot\03-development\v6-to-v9-migration-spec.md"; Target = "$docsRoot\4-technical-specs\d5-migration\v6-to-v9-migration-spec.md" }
    @{ Source = "$docsRoot\03-development\db-migration-v4-to-v6.md"; Target = "$docsRoot\4-technical-specs\d5-migration\db-migration-v4-to-v6.md" }
    @{ Source = "$docsRoot\01-requirements\v6pro-to-v9-migration-analysis.md"; Target = "$docsRoot\4-technical-specs\d5-migration\v6pro-to-v9-migration-analysis.md" }
    @{ Source = "$docsRoot\02-design\v6pro-v9-gap-analysis-final.md"; Target = "$docsRoot\4-technical-specs\d5-migration\v6pro-v9-gap-analysis-final.md" }
    @{ Source = "$docsRoot\02-design\v6pro-ui-page-diff-report.md"; Target = "$docsRoot\4-technical-specs\d5-migration\v6pro-ui-page-diff-report.md" }
    @{ Source = "$docsRoot\04-testing\testing-strategy.md"; Target = "$docsRoot\5-testing\e1-test-layers\testing-strategy.md" }
    @{ Source = "$docsRoot\04-testing\test-catalog.md"; Target = "$docsRoot\5-testing\e2-test-cases\test-catalog.md" }
    @{ Source = "$docsRoot\04-testing\feature-entry-list.md"; Target = "$docsRoot\5-testing\e2-test-cases\feature-entry-list.md" }
    @{ Source = "$docsRoot\03-development\V9-TEST-CASES.md"; Target = "$docsRoot\5-testing\e2-test-cases\V9-TEST-CASES.md" }
    @{ Source = "$docsRoot\04-testing\regression-test-report.md"; Target = "$docsRoot\5-testing\e3-reports\regression-test-report.md" }
    @{ Source = "$docsRoot\04-testing\a11y-contrast-report.md"; Target = "$docsRoot\5-testing\e3-reports\a11y-contrast-report.md" }
    @{ Source = "$docsRoot\04-testing\automation-test-evaluation.md"; Target = "$docsRoot\5-testing\e3-reports\automation-test-evaluation.md" }
    @{ Source = "$docsRoot\03-development\2026-07-05-exception-handling-test-report.md"; Target = "$docsRoot\5-testing\e3-reports\exception-handling-test-report.md" }
    @{ Source = "$docsRoot\04-testing\completeness-profile-batch2.md"; Target = "$docsRoot\5-testing\e3-reports\completeness-profile-batch2.md" }
    @{ Source = "$docsRoot\03-development\completeness-profile-batch3.md"; Target = "$docsRoot\5-testing\e3-reports\completeness-profile-batch3.md" }
    @{ Source = "$docsRoot\02-design\completeness-profile-batch4.md"; Target = "$docsRoot\5-testing\e3-reports\completeness-profile-batch4.md" }
    @{ Source = "$docsRoot\01-requirements\completeness-profile-batch5.md"; Target = "$docsRoot\5-testing\e3-reports\completeness-profile-batch5.md" }
    @{ Source = "$docsRoot\04-testing\optimization-plan.md"; Target = "$docsRoot\5-testing\e4-gates\optimization-plan.md" }
    @{ Source = "$docsRoot\04-testing\complexity-remediation-plan.md"; Target = "$docsRoot\5-testing\e4-gates\complexity-remediation-plan.md" }
    @{ Source = "$docsRoot\04-testing\production-release-checklist-SKILL.md"; Target = "$docsRoot\5-testing\e4-gates\production-release-checklist-SKILL.md" }
    @{ Source = "$docsRoot\02-design\ai-generate-audit-fix-loop.md"; Target = "$docsRoot\6-ai-engineering\f1-prompts\ai-generate-audit-fix-loop.md" }
    @{ Source = "$docsRoot\02-design\ai-memory-layer.md"; Target = "$docsRoot\6-ai-engineering\f3-memory\ai-memory-layer.md" }
    @{ Source